# Generated by Django 4.0.1 on 2022-01-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtype',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='mensaje'),
        ),
    ]
