# Generated by Django 4.0.1 on 2022-02-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_emailtype_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtype',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='emailtype',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='titulo'),
        ),
    ]
