# Generated by Django 4.0.1 on 2022-02-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_alter_emailsendingfact_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtype',
            name='message',
        ),
        migrations.AddField(
            model_name='emailtype',
            name='message_1',
            field=models.TextField(blank=True, null=True, verbose_name='mensaje 1'),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='message_2',
            field=models.TextField(blank=True, null=True, verbose_name='mensaje 2'),
        ),
    ]
