# Generated by Django 4.0.1 on 2022-02-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_remove_emailtype_message_emailtype_message_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtype',
            name='message_1_de',
            field=models.TextField(blank=True, null=True, verbose_name='mensaje 1'),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='message_1_en',
            field=models.TextField(blank=True, null=True, verbose_name='mensaje 1'),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='message_1_es',
            field=models.TextField(blank=True, null=True, verbose_name='mensaje 1'),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='message_2_de',
            field=models.TextField(blank=True, null=True, verbose_name='mensaje 2'),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='message_2_en',
            field=models.TextField(blank=True, null=True, verbose_name='mensaje 2'),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='message_2_es',
            field=models.TextField(blank=True, null=True, verbose_name='mensaje 2'),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='subject_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='subject_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='subject_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject'),
        ),
    ]
