# Generated by Django 4.0.1 on 2022-01-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='bed',
            field=models.PositiveIntegerField(default=1, verbose_name='Camaa pequeñas'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='double_bed',
            field=models.PositiveIntegerField(default=1, verbose_name='Camas doble'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='max_person',
            field=models.PositiveIntegerField(default=1, verbose_name='Max. Huéspedes'),
        ),
    ]
