# Generated by Django 4.0.1 on 2022-01-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_reserva_cleaning_price_reserva_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='cleaning_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=9, verbose_name='Общая цена'),
        ),
    ]
