# Generated by Django 4.0.1 on 2022-01-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_apartment_cleaning_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Dueño de apr')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('phone', models.CharField(max_length=255, verbose_name='Dueño de apr')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Dueño',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='promo_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='código de promoción'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartment', to='apartments.owner'),
        ),
    ]
