# Generated by Django 4.0.1 on 2022-01-25 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartments', '0005_owner_apartment_promo_code_apartment_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Ciente'},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cleaning_price',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='price_per_night',
        ),
        migrations.AddField(
            model_name='booking',
            name='my_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario mio'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='cleaning_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=9, verbose_name='Precio de limpieza'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartment', to='apartments.owner', verbose_name='Dueño'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario de cliente'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creacion de reserva'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'Reserva nueva'), ('in_progress', 'Заказ в обработке'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ получен покупателем')], default='new', max_length=100, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_orders',
            field=models.ManyToManyField(blank=True, related_name='related_customer', to='apartments.Booking', verbose_name='Reservas del cliente'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='check_in',
            field=models.DateField(verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='check_out',
            field=models.DateField(verbose_name='Salida'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio final'),
        ),
    ]
