# Generated by Django 4.0.1 on 2022-01-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_alter_customer_options_remove_reserva_cleaning_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='my_comment',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cleaning_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=9, verbose_name='Общая цена'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=9, verbose_name='Precio por noche'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivo?'),
        ),
    ]
