# Generated by Django 4.0.1 on 2022-01-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_remove_booking_my_comment_reserva_cleaning_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='my_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario mio'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
    ]
