# Generated by Django 4.0.1 on 2022-01-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_booking_my_comment_alter_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='settle',
            field=models.BooleanField(default=False, verbose_name='Liqudado ?'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cleaning_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=9, verbose_name='Precio de limpieza'),
        ),
    ]
