# Generated by Django 4.0.1 on 2022-01-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_booking_settle_alter_reserva_cleaning_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_accept',
            field=models.BooleanField(default=True, verbose_name='Aceptado ?'),
        ),
    ]
