# Generated by Django 4.0.1 on 2022-01-28 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_booking_is_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='amount_persons',
            field=models.PositiveIntegerField(default=1, verbose_name='úmero de huéspedes'),
        ),
        migrations.CreateModel(
            name='BookingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bk_date', to='apartments.booking', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Fechas',
            },
        ),
    ]
