# Generated by Django 4.0.1 on 2022-01-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0011_reserva_amount_persons_bookingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdate',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
