# Generated by Django 4.0.1 on 2022-01-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0012_alter_bookingdate_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingdate',
            options={'verbose_name': 'Fecha'},
        ),
    ]
