# Generated by Django 4.0.1 on 2022-01-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0014_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion de Banco'),
        ),
        migrations.AddField(
            model_name='owner',
            name='banco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='owner',
            name='iban',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Iban'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre de dueño'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Telefono'),
        ),
    ]
