# Generated by Django 4.0.1 on 2022-01-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0015_owner_address_owner_banco_owner_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='booked',
            field=models.BooleanField(default=False, verbose_name='Resrvada'),
        ),
    ]
