# Generated by Django 4.0.1 on 2022-01-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0017_reserva_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='condition',
            field=models.TextField(blank=True, null=True, verbose_name='Condiciones'),
        ),
    ]
