# Generated by Django 4.0.1 on 2022-02-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0018_apartment_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_1', models.TextField()),
                ('info_2', models.TextField()),
                ('info_3', models.TextField()),
                ('info_4', models.TextField()),
                ('info_5', models.TextField()),
                ('info_6', models.TextField()),
                ('info_7', models.TextField()),
                ('info_8', models.TextField()),
            ],
        ),
    ]
