# Generated by Django 4.0.1 on 2022-02-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0020_category_apartment_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='pageinfo',
            options={'verbose_name': 'Info'},
        ),
        migrations.RenameField(
            model_name='pageinfo',
            old_name='info_1',
            new_name='info',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='info_2',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='info_3',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='info_4',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='info_5',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='info_6',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='info_7',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='info_8',
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='title',
            field=models.CharField(default='info', max_length=255, verbose_name='Nombtre'),
        ),
    ]
