# Generated by Django 4.0.1 on 2022-02-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0022_apartment_condition_de_apartment_condition_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nombre')),
                ('text', models.TextField(verbose_name='Mensaje')),
                ('text_es', models.TextField(null=True, verbose_name='Mensaje')),
                ('text_en', models.TextField(null=True, verbose_name='Mensaje')),
                ('text_de', models.TextField(null=True, verbose_name='Mensaje')),
            ],
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='title',
            field=models.CharField(default='info', max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='title_de',
            field=models.CharField(default='info', max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='title_en',
            field=models.CharField(default='info', max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='title_es',
            field=models.CharField(default='info', max_length=255, null=True, verbose_name='Nombre'),
        ),
    ]
