# Generated by Django 4.0.2 on 2022-02-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0023_pagemessage_alter_pageinfo_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemessage',
            options={'verbose_name': 'Mensaje'},
        ),
    ]
