# Generated by Django 4.0.1 on 2022-03-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0025_booking_country_images_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='toilet',
            field=models.PositiveIntegerField(default=1, verbose_name='Baños'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='video_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='código de video'),
        ),
    ]
